version: 2.1

executors:
  buildtime:
    docker:
    - image: nixos/nix:2.2.1
  runtime:
    docker:
    - image: node:10.16.3-alpine

jobs:
  build:
    executor: buildtime
    steps:
      - run: nix-shell --verbose --show-trace shell.nix
      - checkout
      - run: echo "A first hello"
